;
; THIS CODE WILL TURN AN LED ON IF A PUSHBUTTON IS PRESSED
;  OR TURN THE LED OFF IF THE PUSHBUTTON IS NOT PRESSED
; PUSHBUTTON PIN D7
; LED PIN D8
; WRITTEN: 11/15/2017 10:28:58 AM
; EDITED:  06/12/2019 01:55:32 PM
; AUTHOR : Alyssa J. Pasquale, Ph.D.
;

; setup subroutine starts here
; CONFIGURE PORTB BIT 0 (PIN D8) AS OUTPUT
SBI DDRB, 0

; loop subroutine starts here
loop:
; INPUT DATA FROM PIND REGISTER
IN r16, PIND
; MASK DATA FROM PIND REGISTER
ANDI r16, 0x80

; COMPARE REGISTER 16 TO 0x80
CPI r16, 0x80
; IF R16 >= 0x80, TURN ON THE LED
BRSH turn_on_led

; OTHERWISE, TURN OFF THE LED
turn_off_led:
CBI PORTB, 0
; JUMP TO THE START OF THE LOOP
JMP loop

; THIS IS THE TURN ON LED CODE
turn_on_led:
SBI PORTB, 0

; TELL THE CODE TO REPEAT AGAIN FROM THE BEGINNING OF main
JMP loop
