;
; THIS CODE WILL TURN AN LED ON IF A PUSHBUTTON IS PRESSED
;  OR TURN THE LED OFF IF THE PUSHBUTTON IS NOT PRESSED
; PUSHBUTTON PIN D7
; LED PIN D8
; WRITTEN: 11/15/2017 10:28:58 AM
; EDITED:  06/12/2019 01:55:32 PM
; AUTHOR : Alyssa J. Pasquale, Ph.D.
;

JMP main

main:
; CONFIGURE PORTB BIT 0 (PIN D8) AS OUTPUT
SBI	DDRB, 0
; CLEAR PORTB BIT 0
CBI PORTB, 0

; INPUT DATA FROM PIND REGISTER
IN r16, PIND

; COMPARE REGISTER 16 TO 0x80
CPI r16, 0x80
; IF R16 >= 0x80, TURN ON THE LED
BRSH turn_on_led

; OTHERWISE, TURN OFF THE LED
turn_off_led:
CBI PORTB, 0
; JUMP TO THE END, SKIP THE TURN ON LED SECTION
JMP end

; THIS IS THE TURN ON LED CODE
turn_on_led:
SBI PORTB, 0

; TELL THE CODE TO REPEAT AGAIN FROM THE BEGINNING OF main
end:
JMP main